### ISSUE TITLE
S3 Pytorch Dataloading

### ISSUE THREAD

**Issue by zlapp** [areshytko/articles#1]
Hi,

Thanks for the great in-depth tutorial with src code. 
Looking forward to testing it out.

I was wondering what is the correct way, given the dataset is on S3, to train in the distributedly? 

Any pointers would be big help.
Was thinking of extending your src and making a toy example by uploading mnist to S3.

**Comment by areshytko** [comment]
@zlapp Hi,

thank you.

You need to read from S3 into every node. The best way to do this is with new PyTorch-Lightning functionality [LightningDataModule](https://pytorch-lightning.readthedocs.io/en/latest/datamodules.html) (please, look at `prepare_data()` method).

Also, there is a more performant but a bit more expensive way: to use AWS [FSx for Lustre](https://aws.amazon.com/fsx/lustre/). This is a high-performant AWS shared file system that allows to mount S3 buckets seamlessly. 

Also, please have a look at the [source code for the second part of the article](https://github.com/areshytko/articles/tree/master/ansible-ml-2). I haven't written it yet but the code is basically finished. It doesn't solve exactly your problem, but I've implemented uploading the experiment results to S3.

Hope, it helped you

**Comment by zvicortica** [comment]
Awesome will take a look!
Thanks again, looking forward to reading the next blogpost.

**Comment by zlapp** [comment]
Awesome, thanks again!
Looking forward to reading the next blog post.
